config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/about', to: 'pages#about'
  get '/portfolio', to: 'pages#portfolio'
  get '/movie_finder', to: 'pages#movie_finder'
  get '/old_film_work', to: 'pages#old_film_work'
  get '/contact', to: 'pages#contact'
  get '/chat', to: 'pages#chat'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  end

  def movie_finder
  end

  def old_film_work
  end

  def contact
  end

  def chat
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthentication</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id="page-container">
      <div>
          <%= render "shared/navbar"%>
      </div>
      <div id="content-wrap" style="margin-top:32px;">
        <%= yield %>
      </div>
      <div>
        <%= render "shared/footer" %>
        <%= render "shared/flashes" %>
      </div>
    </div>
  </body>
</html>

app/views/pages/chat.hmtl.erb
<section class="side-bar">
  <button>New Chat</button>
  <div class="history"></div>
  <div class="nav">
    <p>Made by Sam</p>
  </div>
</section>

<section class="main-chat">
  <h1>SamGPT</h1>
  <p id="output"></p>
  <div class="bottom-section">
    <div class="input-container">
      <input />
      <div id="submit"></div>
    </div>
  </div>
  <p class="info">
    Chat GPT Apr. 24th Version.
  </p>
</section>


<script src="app.js"></script>

app/views/pages/home.html.erb
<html>
  <head>
    <title>Sam's Portfolio</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <section id="hero">
      <h1>Hi, I'm Sam</h1>
      <p>I'm a web developer based in San Francisco, California.</p>
      <button>View my portfolio</button>
    </section>

    <section id="about">
      <h2>About Me</h2>
      <p>I'm a full-stack web developer with experience building websites and web applications using Ruby on Rails, JavaScript, and HTML/CSS.</p>
      <p>Some of my recent projects include:</p>
      <ul>
        <li><a href="#">Project 1</a></li>
        <li><a href="#">Project 2</a></li>
        <li><a href="#">Project 3</a></li>
      </ul>
    </section>

    <section id="portfolio">
      <h2>Portfolio</h2>
      <p>Here are some examples of my recent work:</p>
      <ul>
        <li><a href="#"><img src="project1.jpg" alt="Project 1"></a></li>
        <li><a href="#"><img src="project2.jpg" alt="Project 2"></a></li>
        <li><a href="#"><img src="project3.jpg" alt="Project 3"></a></li>
      </ul>
    </section>

    <section id="contact">
      <h2>Contact Me</h2>
      <p>Get in touch with me to discuss your next web development project:</p>
      <form>
        <input type="text" placeholder="Name">
        <input type="email" placeholder="Email">
        <textarea placeholder="Message"></textarea>
        <button>Send Message</button>
      </form>
    </section>

    <script type="text/javascript" src="script.js"></script>
  </body>
</html>

app/views/pages/old_film_work.html.erb
<div id="carouselExampleIndicators" class="carousel slide w-50" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="d-flex justify-content-center align-items-center">
        <iframe src="https://player.vimeo.com/video/86345360" width="640" height="360" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <p>Autodesk Maya 3D animation projeect of a submarine following a clown fish through a sunken city</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex justify-content-center align-items-center">
        <iframe src="https://player.vimeo.com/video/110795460" width="640" height="360" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <p>Composition project I made in after effects using greenscreens and rotobrush techniques</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex justify-content-center align-items-center">
        <iframe src="https://player.vimeo.com/video/115489082" width="640" height="360" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <p>My advanced computer animation project about a convict trying to escape a dystopian city. Created in Maya and composited in after effects. Music is Stations II by Minilogue</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex justify-content-center align-items-center">
        <iframe src="https://player.vimeo.com/video/90485767" width="640" height="360" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <p>Interviews of three different artists for a class project</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex justify-content-center align-items-center">
        <iframe src="https://player.vimeo.com/video/90481426" width="640" height="360" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <p>A class project, with a cast of one and a crew of one. Josh is blind to the outside world, and an extra-terrestrial helps him see the world from another perspective.</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex justify-content-center align-items-center">
        <iframe src="https://player.vimeo.com/video/87291217" width="640" height="360" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <p>For a Video Field Production Class. Tommy Harkey is prescribed Valium for his seizures. Upon taking them the protagonist suffers from disturbing hallucinations.</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex justify-content-center align-items-center">
        <iframe src="https://player.vimeo.com/video/122278932" width="640" height="360" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <p>This is the description for Carousel Item 1</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex justify-content-center align-items-center">
        <iframe src="https://player.vimeo.com/video/107733428" width="640" height="360" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <p>This is the description for Carousel Item 1</p>
      </div>
    </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<%# <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <!-- Add more indicators for each video -->
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <iframe src="https://player.vimeo.com/video/86345360" width="640" height="360" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="item">
      <iframe src="https://player.vimeo.com/video/110795460" width="640" height="360" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="item">
      <iframe src="https://player.vimeo.com/video/115489082" width="640" height="360" frameborder="0" allowfullscreen></iframe>
    </div>

    <!-- Add more slides for each video -->
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div> %>




<%# <iframe src="https://player.vimeo.com/video/86345360" width="640" height="360" frameborder="0" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/110795460" width="640" height="360" frameborder="0" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/115489082" width="640" height="360" frameborder="0" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/122278932" width="640" height="360" frameborder="0" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/90485767" width="640" height="360" frameborder="0" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/90481426" width="640" height="360" frameborder="0" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/87291217" width="640" height="360" frameborder="0" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/107733428" width="640" height="360" frameborder="0" allowfullscreen></iframe> %>

app/views/pages/portfolio.html.erb
<div class="text-center mb-4">
  <h2 style="font-size: 2.5rem; font-weight: 700;">Portfolio</h2>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="card h-100">
      <%= link_to image_tag("tangobravo.png", class: "card-img-top"), "https://www.tangobravo.pro/" %>
      <div class="card-body d-flex flex-column">
        <h5 class="card-title text-center"><%= link_to "Tango Bravo", "https://www.tangobravo.pro/" %></h5>
        <p class="card-text text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec massa purus. Nulla facilisi.</p>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card h-100">
      <%= link_to image_tag("proton.png", class: "card-img-top"), "https://www.protoncars.pro" %>
      <div class="card-body d-flex flex-column">
        <h5 class="card-title text-center"><%= link_to "Proton", "https://www.protoncars.pro" %></h5>
        <p class="card-text text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec massa purus. Nulla facilisi.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="text-center footer">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4 icons  link-footer">
      <a
        class=" linkedin-icon text-white btn btn-floating m-1"
        href="https://www.linkedin.com/in/sam-musler/"
        role="button"
        ><i class="fab fa-linkedin"></i
      ></a>
      <a
        class=" github-icon text-white btn btn-floating m-1"
        href="https://github.com/smus31"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
      <!-- Facebook -->
      <a
        class="facebook-icon text-white btn btn-floating m-1"
        href="https://www.facebook.com/sam.musler"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="twitter-icon text-white btn btn-floating m-1"
        href="https://twitter.com/SamMusler"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Instagram -->
      <a
        class=" instagram-icon text-white btn btn-floating m-1"
        href="https://www.instagram.com/smus31/"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>
    </section>
  </div>

  <div class="text-center p-3 finalfooter text-white">
    © 2023 Tango Bravo. All rights reserved.

  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Portfolio', portfolio_path %></li>
      <li><%= link_to 'Movie Finder', movie_finder_path %></li>
      <li><%= link_to 'Old Film Work', old_film_work_path %></li>
      <li><%= link_to 'Chat', chat_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>

    </ul>
  </nav>
</header>